name: Ruby - Rails Gems Spec Workflow
on:
  workflow_call:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: [3.1, 3.2, 3.3, 3.4, head, truffleruby, truffleruby-head]
        rails: ['~> 6.1.0', '~> 7.0.0', '~> 8.0.0', '>= 0']
        exclude:
          - rails: '~> 8.0.0'
            ruby: 3.1
    runs-on: ${{ matrix.os }}
    env:
      CI_RAILS_VERSION: ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rspec
